# Generated by Django 5.1 on 2024-09-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_media', models.CharField(choices=[('livre', 'Livre'), ('dvd', 'DVD'), ('cd', 'CD'), ('jeu_de_plateau', 'Jeu de Plateau')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('auteur', models.CharField(blank=True, max_length=255, null=True)),
                ('artiste', models.CharField(blank=True, max_length=255, null=True)),
                ('createur', models.CharField(blank=True, max_length=255, null=True)),
                ('realisateur', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
    ]
